### ISSUE TITLE
Weird connecting issue

### ISSUE THREAD

**Issue by FaNim21** [tinodo/obsclient#7]
Hello i want to ask about connecting to obs

```
bool isConnected = await Client.ConnectAsync(true, CurrentChosen!.Password, "localhost", CurrentChosen.Port);
Client.ConnectionClosed += (x, args) => { MessageBox.Show("Lost connection"); };
if (isConnected)
{
    try
    {
        //await Task.Delay(1000);

        await Client.SetCurrentSceneCollection(CurrentChosen.SceneCollection);
        await Client.SetCurrentProgramScene(CurrentChosen.Scene);

        MessageBox.Show("Connected to obs succesfully");
    }
    catch (Exception ex)
    {
        MessageBox.Show($"Error: {ex.Message} - {ex.StackTrace}");
        Disconnect();
        return;
    }
}
```

because I am experiencing issues with the isConnected variable. It should be true if it is really connected to OBS, but without setting a delay like 500-1000ms, when I attempt to set the current scene collection, I get an error stating that OBS is not connected. It seems like there is an issue with the waiting process because my variable is true, but I still receive an error indicating that it is not connected. Maybe I've done something wrong?

**Comment by tinodo** [comment]
The behavior you are seeing is as designed. The fact that **ConnectAsync** returns **true** merely means that a WebSockets connection to OBS Studio could be established. If you don't use authentication, you can immediately start sending commands to OBS Studio. If you _are_ using authentication, you have to wait for the authentication process to complete. (The **ConnectionState** property have the value **Authenticating** as long as the authentication hasn't completed yet.) After the authentication is done, the **ConnectionState** either is **Disconnected** (the authentication failed and you are disconnected from OBS Studio) or it is **Authenticated**. You can achieve this by simply waiting after calling **ConnectAsync**, but there are a more elegant solutions.

You can subscribe to the **PropertyChanged** event and see whether the **ConnectionState** property has the desired value (e.g. "Connected"), and then continue. Or you can wait for the **ConnectionState** to become **Connected** and then continue. This will prevent you having to wait an arbitrary amount of time. In essence, you wait for at most a certain amount of milliseconds, or until the authentication has happened; whichever occurs first.

An example:

```
            var client = new ObsClient();
            TaskCompletionSource<bool> tcs = new();
            client.PropertyChanged += (sender, eventArgs) =>
            {
                if (eventArgs.PropertyName == "ConnectionState" && client.ConnectionState == ConnectionState.Connected)
                {
                    tcs.TrySetResult(true);
                }
            };
            var isAuthenticated = false;
            var isConnected = await client.ConnectAsync(true, "P@ssw0rd");
            if (isConnected)
            {
                using CancellationTokenSource cts = new(1000); // Wait at most 1000ms for the authentication to finish.
                using var ctr = cts.Token.Register(() => tcs.TrySetCanceled(), false);
                try
                {
                    isAuthenticated = await tcs.Task;
                }
                catch (TaskCanceledException)
                {
                    // Authentication timed out or is invalid
                }
                finally
                {
                    _ = ctr.Unregister();
                }
            }

            await Console.Out.WriteLineAsync($"Connected: {isConnected}, Authenticated: {isAuthenticated}");
```

**Comment by FaNim21** [comment]
thank you for help i will check this out then <3
