### ISSUE TITLE
OBSStudioClient.ObsClient.SetInputSettings has some invalid arguments

### ISSUE THREAD

**Issue by AndreZila01** [tinodo/obsclient#9]
Hey, 

i'm new on OBS Websocket 5.0.0 and i would like use "SetSourceSettings", but on recent version of websocket the request are replaced by "SetInputSettings", but when i make the request i recived this message error: "Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'The best overloaded method match for 'OBSStudioClient.ObsClient.SetInputSettings(string, System.Collections.Generic.Dictionary<string,object>, bool)' has some invalid arguments'.

![image](https://github.com/tinodo/obsclient/assets/56931353/6cf3610e-9469-44c3-ade9-804384d5e703)

Code: 
```
var settinsgs = await client.SetInputSettings("Image12", JsonConvert.DeserializeObject<dynamic>("{file: '/home/admin123/Pictures/Pokemon-Legends-Arceus-Profile-Picture.webp'}"), false);//SendRequestAndWaitAsync()
```

I would like know, what i'm doing wrong.
Thanks

**Comment by tinodo** [comment]
Looking at the error, it's most like not your fault. :-)
I will check out what's wrong!

Thanks for the notice!
